apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T03:45:02Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2857"
  uid: 07939bd7-2633-4ec3-aee6-d169b5797c8a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.17.219
  clusterIPs:
  - 10.105.17.219
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30633
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
